### ISSUE TITLE
Information regarding L1/L2/L3 caches in the evaluated system.

### ISSUE THREAD

**Issue by geraldofojunior** [lac-dcc/benchMetrics#1]
Hi,

Thanks for putting out such analyses! 

I want to ask if you can include in the README the sizes of the L1, L2, and L3 caches in the evaluated system.

Thank you once again.

**Comment by geraldofojunior** [comment]
Also, information regarding the input dataset would be helpful.

**Comment by 1LucasVictor** [comment]
Hi Geraldo,



> Hi,
> 
> Thanks for putting out such analyses!
> 
> I want to ask if you can include in the README the sizes of the L1, L2, and L3 caches in the evaluated system.
> 
> Thank you once again.

Hi Geraldo,

The sizes of the L1, L2, and L3 caches are available in the README now. Thanks for the suggestion!

**Comment by 1LucasVictor** [comment]
> Also, information regarding the input dataset would be helpful.

I've added it too!
